# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: mimiops-mcp

dist: bin
builds:
  - id: default
    main: ./cmd/mimiops-mcp
    binary: bin/mimiops-mcp
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

changelog:
  disable: true

archives:
  - formats: ["binary"]

dockers_v2:
  - id: default
    flags:
      - --target=release
    images:
      - ghcr.io/sergelogvinov/mimiops-mcp
    tags:
      - "v{{.Version}}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      io.modelcontextprotocol.server.name: "io.github.sergelogvinov/mimiops-mcp"
    annotations:
      org.opencontainers.image.description: "Mimi Ops is an opinionated MCP server for Kubernetes"
      org.opencontainers.image.licenses: "Apache-2.0"
      org.opencontainers.image.source: "https://github.com/sergelogvinov/mimiops-mcp"
      org.opencontainers.image.url: "{{.GitURL}}"

docker_digest:
  name_template: "digest.txt"

docker_signs:
  - id: default
    cmd: cosign
    args:
      - sign
      - "--yes"
      - "${artifact}"
    output: true

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - artifacts: checksum
    signature: "${artifact}.sigstore.json"
    cmd: cosign
    args:
      - sign-blob
      - "--yes"
      - "--bundle=${signature}"
      - "${artifact}"
    output: true

mcp:
  name: io.github.sergelogvinov/mimiops-mcp
  title: "Mimi Ops mcp server for Kubernetes"
  description: "Mimi Ops is an opinionated MCP server for Kubernetes"
  homepage: "https://github.com/sergelogvinov/mimiops-mcp"
  auth:
    type: github-oidc
    token: "{{ .Env.GITHUB_TOKEN }}"
  repository:
    url: "https://github.com/sergelogvinov/mimiops-mcp"
    source: github
    id: "1334949924"
  # https://github.com/goreleaser/goreleaser/discussions/6251
  packages:
    - registry_type: oci
      identifier: "ghcr.io/sergelogvinov/mimiops-mcp:v{{ .Version }}"
      transport:
        type: stdio
    # - registry_type: mcpb
    #   identifier: "@sergelogvinov/mimiops-mcp"
    #   transport:
    #     type: stdio
