# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: mimiops-mcp

dist: bin
builds:
  - id: default
    main: ./cmd/mimiops-mcp
    binary: bin/mimiops-mcp
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    goarm64:
      - v8.0
    hooks:
      post: make release-mcpb OS={{ .Os }} ARCH={{ .Arch }} VERSION={{ .Version }} BUNDLE_DIR={{ dir .Path }}/bundle

snapshot:
  version_template: edge

changelog:
  disable: true

archives:
  - formats: [binary]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

  # - id: default
  #   ids:
  #     - default
  #   name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  #   formats:
  #     - tar.gz
  #   format_overrides:
  #     - formats:
  #         - zip
  #       goos: windows
  #   files:
  #     - LICENSE

homebrew_casks:
  - name: mimiops-mcp
    description: MimiOps is an opinionated MCP server for Kubernetes
    homepage: https://github.com/sergelogvinov/mimiops-mcp
    license: Apache-2.0

    directory: Casks
    commit_author:
      name: sergelogvinov
      email: 5407715+sergelogvinov@users.noreply.github.com
    repository:
      owner: sergelogvinov
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TOKEN }}"

    binaries:
      - mimiops-mcp

    # Bug in goreleaser v2.17.1?: target is bin/mimiops-mcp,
    # but it should be mimiops-mcp, so we need to override it in custom_block
    custom_block: |
      arch arm: "arm64", intel: "amd64"
      os macos: "darwin", linux: "linux"
      binary "mimiops-mcp_#{os}_#{arch}", target: "mimiops-mcp"

    # Bug?
    # need set full name of binary in postflight - mimiops-mcp_darwin_#{arch}
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mimiops-mcp_darwin_#{arch}"]
          end

dockers_v2:
  - id: default
    flags:
      - --target=release
    images:
      - ghcr.io/sergelogvinov/mimiops-mcp
    tags:
      - "v{{.Version}}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      io.modelcontextprotocol.server.name: "io.github.sergelogvinov/mimiops-mcp"
      io.artifacthub.package.readme-url: "https://raw.githubusercontent.com/sergelogvinov/mimiops-mcp/main/README.md"
      io.artifacthub.package.license: "Apache-2.0"
    annotations:
      org.opencontainers.image.name: "{{ .ProjectName }}"
      org.opencontainers.image.description: "MimiOps is an opinionated MCP server for Kubernetes"
      org.opencontainers.image.licenses: "Apache-2.0"
      org.opencontainers.image.source: "https://github.com/sergelogvinov/mimiops-mcp"
      org.opencontainers.image.url: "{{ .GitURL }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"

docker_digest:
  name_template: "digest.txt"

docker_signs:
  - id: default
    cmd: cosign
    args:
      - sign
      - "--yes"
      - "${artifact}"
    output: true

checksum:
  name_template: checksums.txt
  algorithm: sha256
  extra_files:
    - glob: ./mimiops-mcp_*.mcpb

signs:
  - artifacts: checksum
    signature: "${artifact}.sigstore.json"
    cmd: cosign
    args:
      - sign-blob
      - "--yes"
      - "--bundle=${signature}"
      - "${artifact}"
    output: true

publishers:
  - name: mcpb
    cmd: gh release upload {{ .Tag }} mimiops-mcp_{{ .Os }}_{{ .Arch }}.mcpb --clobber
    env:
      - GH_TOKEN={{ .Env.GITHUB_TOKEN }}

mcp:
  name: io.github.sergelogvinov/mimiops-mcp
  title: "MimiOps mcp server for Kubernetes"
  description: "MimiOps is an opinionated MCP server for Kubernetes"
  homepage: "https://github.com/sergelogvinov/mimiops-mcp"
  auth:
    type: github-oidc
    token: "{{ .Env.GITHUB_TOKEN }}"
  repository:
    url: "https://github.com/sergelogvinov/mimiops-mcp"
    source: github
    id: "1334949924"
  # https://github.com/goreleaser/goreleaser/discussions/6251
  packages:
    - registry_type: oci
      identifier: "ghcr.io/sergelogvinov/mimiops-mcp:v{{ .Version }}"
      transport:
        type: stdio
    # - registry_type: mcpb
    #   identifier: "@sergelogvinov/mimiops-mcp"
    #   transport:
    #     type: stdio
